"""add footer_note to ContactPage

Revision ID: 4b4ff3ba164b
Revises: d646cb512231
Create Date: 2025-10-10 14:22:23.785701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4ff3ba164b'
down_revision = 'd646cb512231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footer_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_page', schema=None) as batch_op:
        batch_op.drop_column('footer_note')

    # ### end Alembic commands ###
