"""initial migration

Revision ID: 623dd9782637
Revises: 
Create Date: 2025-09-24 02:22:33.653192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623dd9782637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=False)

    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_email'), ['email'], unique=False)

    op.create_table('social_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_user_platform')
    )
    op.create_table('project_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_carousel', sa.Boolean(), nullable=False),
    sa.Column('slide_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.create_index('ix_img_cat_slide', ['category_id', 'slide_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_image_is_carousel'), ['is_carousel'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_image_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_image_slide_key'), ['slide_key'], unique=False)

    op.create_table('project_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_carousel', sa.Boolean(), nullable=False),
    sa.Column('slide_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_video_is_carousel'), ['is_carousel'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_video_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_video_slide_key'), ['slide_key'], unique=False)
        batch_op.create_index('ix_vid_cat_slide', ['category_id', 'slide_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_video', schema=None) as batch_op:
        batch_op.drop_index('ix_vid_cat_slide')
        batch_op.drop_index(batch_op.f('ix_project_video_slide_key'))
        batch_op.drop_index(batch_op.f('ix_project_video_position'))
        batch_op.drop_index(batch_op.f('ix_project_video_is_carousel'))

    op.drop_table('project_video')
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_image_slide_key'))
        batch_op.drop_index(batch_op.f('ix_project_image_position'))
        batch_op.drop_index(batch_op.f('ix_project_image_is_carousel'))
        batch_op.drop_index('ix_img_cat_slide')

    op.drop_table('project_image')
    op.drop_table('social_link')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_email'))

    op.drop_table('message')
    op.drop_table('cv')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_index(batch_op.f('ix_category_order'))

    op.drop_table('category')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
